name: IPRanges - Build & Test

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
    
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
        
    - name: Build
      run: dotnet build --configuration Release
      working-directory: ./src

    - name: Run unit tests
      run: dotnet test --configuration Release
      working-directory: ./src